#!/bin/bash
# 
# create new projects
# should:
#   - intialize a git repo
#   - create a .gitignore
#   - create language-specific things:
#       - golang:
#           - dep init
#       - python:
#           - pipenv version 3.6

# $1 - language name
# $2 - project name

LANGUAGE_NAME=$1
PROJECT_NAME=$2

err() {
  echo "[$(date +'%Y-%m-%dT%H:%M:%S%z')]: $@" >&2
}

init_dir() {
  echo "Creating a ${LANGUAGE_NAME} project named ${PROJECT_NAME}"
  mkdir ${PROJECT_NAME}
}

init_git() {
  cd ${PROJECT_NAME}
  git init
  touch .gitignore
  cd ..
}

init_golang() {
  # dep init
  # that's... it?
  cd ${PROJECT_NAME}
  echo "Running 'dep init'"
  dep init
}

init_python() {
  # pipenv version 3.6
  # that's... it?
  cd ${PROJECT_NAME}
  echo "Initializing Python virtualenv using pipenv"
  pipenv --python 3.6
}

#####################################################
# main : create project dir
# initialize dir with git and language-specific tools
#####################################################
main() {
  if [[ ${LANGUAGE_NAME} != "python" && ${LANGUAGE_NAME} != "golang" ]]; then
    err "${LANGUAGE_NAME} projects are not supported"
    exit 1
  fi
  echo "Creating a ${LANGUAGE_NAME} project named ${PROJECT_NAME}"
  init_dir
  init_git
  case "${LANGUAGE_NAME}" in
    golang) init_golang ;;
    python) init_python ;;
  esac
  echo "Done"
}

main
