#!/bin/bash
# 
# create new projects
# should:
#   - intialize a git repo
#   - create a .gitignore
#   - create language-specific things:
#       - golang:
#           - dep init
#       - python:
#           - pipenv version 3.6

# $1 - language name
# $2 - project name

init_golang() {
  # dep init
  # that's... it?
  echo "Running 'dep init'"
  dep init
}

init_python() {
  # pipenv version 3.6
  # that's... it?
  echo "Initializing Python virtualenv using pipenv"
  pipenv --python 3.6
}

main() {
  # main:
  # mkdir project_name && cd project_name
  # git init
  language_name=$1
  project_name=$2
  echo ${language_name} ${project_name}
  echo "Creating a ${language_name} project named ${project_name}"
  mkdir ${project_name} && cd ${project_name}
  git init
  touch .gitignore
  case "${language_name}" in
    golang) init_golang ;;
    python) init_python ;;
    *) echo "${language_name} projects are not supported" ;;
  esac
  echo "Done"
}

main $1 $2
